"""
Django settings for geodjango project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
from os import getenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = getenv('NATURWB_DJANGO_SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = getenv('NATURWB_DJANGO_DEBUG')
if DEBUG is None:
    DEBUG = False
else:
    DEBUG = DEBUG.upper() == "TRUE"

ALLOWED_HOSTS = [
    "naturwb.dev.wwl-web.de",
    "localhost",
    "127.0.0.1",
    "naturwb.de",
    "www.naturwb.de"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'leaflet',
    'sitetree',
    'request', # for statistics
    'django_q', # for task queue
    'google_site_verification', 
    # own
    'naturwb',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'request.middleware.RequestMiddleware',
]

ROOT_URLCONF = 'geodjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.joinpath("templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'geodjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default':{
        'ENGINE': 'django.db.backends.postgresql',#'django.contrib.gis.db.backends.postgis'
        'NAME': 'naturwb',
        'USER': 'naturwb',
        'PASSWORD': getenv('NATURWB_DB_PWD'),
        'HOST': 'gamma.joengel.de',
        'PORT': '5432',
        }

}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "naturwb/static",
    # BASE_DIR / "dashboard/static"
]

STATIC_ROOT = BASE_DIR / "static_root" # static directory on the server side to deploy data to, use manage.py collectstatic to fill
# STATIC_ROOT = "/var/www/googlemaps/naturwb/static"

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# leflet configuration
LEAFLET_CONFIG = {
    #'SRID':"EPSG:31467",
    'TILES_EXTENT': [7.5000, 47.2700, 10.5000, 55.0600],#[924861,6375196,985649,6448688],
    'DEFAULT_CENTER': (51.351, 10.459),
    'DEFAULT_ZOOM': 6,
    'NO_GLOBALS': False, # neu
    'PLUGINS': { # neu
        'forms': {
            'auto-include': True
        }
    }
}


# CSFR Security
if DEBUG:
    SECURE_SSL_REDIRECT = False
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True

# User authentification
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# for user statistics request
REQUEST_LOG_IP=False
REQUEST_LOG_USER=False

# Configure your Q cluster
# More details https://django-q.readthedocs.io/en/latest/configure.html
Q_CLUSTER = {
    "name": "naturwb",
    "orm": "default",  # Use Django's ORM + database for broker
    "timeout": 5,
    "max_attempts": 4,
    "retry": 30
}

GOOGLE_SITE_VERIFICATION_FILE = "google0d19707509d795cb.html"

# for django-plotly-dash
##########################
# ASGI_APPLICATION = 'dashboard.routing.application' 
# ASGI_APPLICATION = 'dashboard.asgi.application'


# INSTALLED_APPS.extend([	
#     'bootstrap4',
#     'django_plotly_dash.apps.DjangoPlotlyDashConfig',
#     'channels',
#     'dpd_static_support',
#     # own
#     'dashboard'
#     ])

# MIDDLEWARE.extend([# Adding additional MIDDLEWARE
# 	'whitenoise.middleware.WhiteNoiseMiddleware',
# 	'django_plotly_dash.middleware.BaseMiddleware',
#     'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
# ])

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',

#     'whitenoise.middleware.WhiteNoiseMiddleware',

#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',

#     'django_plotly_dash.middleware.BaseMiddleware',
#     'django_plotly_dash.middleware.ExternalRedirectionMiddleware',

#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#     'django_plotly_dash.finders.DashAssetFinder',
#     'django_plotly_dash.finders.DashComponentFinder',
#     'django_plotly_dash.finders.DashAppDirectoryFinder',
# ]

# X_FRAME_OPTIONS = 'SAMEORIGIN'

# ROOT_URLCONF = "geodjango.urls"

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient"
#         },
#         "KEY_PREFIX": "dpd-demo"
#     }
# }

# Channels config, to use channel layers

# CHANNEL_LAYERS = {
#     'default': {
#         'BACKEND': 'channels_redis.core.RedisChannelLayer',
#         'CONFIG': {
#             'hosts': [('127.0.0.1', 6379),],
#         },
#     },
# }

# PLOTLY_DASH = {

#     # Route used for the message pipe websocket connection
#     "ws_route" :   "dpd/ws/channel",

#     # Route used for direct http insertion of pipe messages
#     "http_route" : "dpd/views",

#     # Flag controlling existince of http poke endpoint
#     "http_poke_enabled" : True,

#     # Insert data for the demo when migrating
#     "insert_demo_migrations" : False,

#     # Timeout for caching of initial arguments in seconds
#     "cache_timeout_initial_arguments": 60,

#     # Name of view wrapping function
#     "view_decorator": "django_plotly_dash.access.login_required",

#     # Flag to control location of initial argument storage
#     "cache_arguments": True,

#     # Flag controlling local serving of assets
#     "serve_locally": False,

#     "stateless_loader" : "demo.scaffold.stateless_app_loader",

# }

# PLOTLY_COMPONENTS = [

#     # Common components
#     'dash_core_components',
#     'dash_html_components',
#     'dash_renderer',

#     # django-plotly-dash components
#     'dpd_components',
#     # static support if serving local assets
#     'dpd_static_support',

#     # Other components, as needed
#     'dash_bootstrap_components',
# ]
