# Generated by Django 3.1.4 on 2020-12-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simgenclcnre',
            name='area',
            field=models.IntegerField(verbose_name='area'),
        ),
    ]
