# Generated by Django 3.1.4 on 2020-12-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0002_auto_20201215_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='simgenclcnre',
            options={'managed': False},
        ),
    ]
