# Generated by Django 3.1.4 on 2020-12-16 15:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0003_auto_20201216_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchPolygon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterModelTable(
            name='simgenclcnre',
            table='sim_gen_clc_nre',
        ),
    ]
