# Generated by Django 3.1.4 on 2020-12-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0004_auto_20201216_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpolygon',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
        migrations.AlterField(
            model_name='searchpolygon',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchpolygon',
            name='user',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
