# Generated by Django 3.1.4 on 2020-12-29 14:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0005_auto_20201216_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanuJoinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sim_id', models.IntegerField(blank=True, null=True)),
                ('bf_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_lanu_join',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanuParasModel',
            fields=[
                ('lanu_id', models.IntegerField(db_column='lanu_ID', primary_key=True, serialize=False)),
                ('baeume', models.IntegerField(blank=True, db_column='Baeume', null=True)),
                ('versiegelung', models.IntegerField(blank=True, db_column='Versiegelung', null=True)),
                ('lanu_code', models.IntegerField(blank=True, null=True)),
                ('mpd_v', models.IntegerField(blank=True, null=True)),
                ('mpl_v', models.IntegerField(blank=True, null=True)),
                ('mpd_h', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_lanu_paras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LookupModel',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gen_id', models.IntegerField(blank=True, null=True)),
                ('nat_id', models.IntegerField(blank=True, null=True)),
                ('lanu_id', models.IntegerField(blank=True, null=True)),
                ('clc_code', models.IntegerField(blank=True, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25832)),
            ],
            options={
                'db_table': 'tbl_lookup_polygons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimulationModel',
            fields=[
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25832)),
                ('sim_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gen_id', models.IntegerField(blank=True, null=True)),
                ('tkle_nr', models.IntegerField(blank=True, null=True)),
                ('nrkart', models.IntegerField(blank=True, null=True)),
                ('sym_nr', models.IntegerField(blank=True, null=True)),
                ('buek_flag', models.SmallIntegerField(blank=True, null=True)),
                ('stat_id', models.IntegerField(blank=True, null=True)),
                ('wea_flag', models.SmallIntegerField(blank=True, null=True)),
                ('wea_dist', models.IntegerField(blank=True, null=True)),
                ('wea_n_wihj', models.DecimalField(blank=True, db_column='wea_n-wihj', decimal_places=65535, max_digits=65535, null=True)),
                ('wea_n_sohj', models.DecimalField(blank=True, db_column='wea_n-sohj', decimal_places=65535, max_digits=65535, null=True)),
                ('wea_et', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wea_t', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sl_mean', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sl_flag', models.SmallIntegerField(blank=True, null=True)),
                ('sl_dist', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('lanu_key', models.IntegerField(blank=True, null=True)),
                ('lanu_flag', models.SmallIntegerField(blank=True, null=True)),
                ('sl_std', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sl_count', models.IntegerField(blank=True, null=True)),
                ('wea_t_std', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wea_n_wihj_std', models.DecimalField(blank=True, db_column='wea_n-wihj_std', decimal_places=65535, max_digits=65535, null=True)),
                ('wea_n_sohj_std', models.DecimalField(blank=True, db_column='wea_n-sohj_std', decimal_places=65535, max_digits=65535, null=True)),
                ('wea_et_std', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('wea_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_simulation_polygons',
                'managed': False,
            },
        ),
    ]
