# Generated by Django 3.1.4 on 2021-02-22 11:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0006_auto_20201229_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_shp', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=25832)),
                ('timestamp', models.DateTimeField()),
                ('n', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('et', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q_oa_za', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('q_gwnb', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('kapA', models.DecimalField(blank=True, db_column='kap.A.', decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'naturwb_results_saved',
                'managed': False,
            },
        ),
        
    ]
