# Generated by Django 3.1.4 on 2021-02-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0007_auto_20210222_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchPolygon',
        ),
        migrations.DeleteModel(
            name='SimGenClcNre',
        ),
    ]
