# Generated by Django 3.1.4 on 2021-02-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0008_auto_20210222_1826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedResults',
        ),
    ]
