# Generated by Django 3.1.7 on 2021-02-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0009_delete_savedresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaturwbSettings',
            fields=[
                ('name', models.TextField(db_column='name', primary_key=True, serialize=False)),
                ('value', models.TextField()),
            ],
            options={
                'db_table': 'naturwb_settings',
                'managed': False,
            },
        ),
    ]
