# Generated by Django 3.1.7 on 2021-02-23 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naturwb', '0010_naturwbsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='naturwbsettings',
            options={},
        ),
    ]
